### ISSUE TITLE
Include FIP header on team page.

### ISSUE THREAD

**Issue by britthurley** [dtf-ein/dtf-ein.github.io#25]
A tip from a friendly source strong hints that we should include the FIP header on our site.

Example here: https://digital.canada.ca/

**Comment by patheard** [comment]
I'll make it happen.

**Comment by patheard** [comment]
I've added the SSC FIP to the top of the [content pages](https://dtf-ein.github.io/home/). 

Few comments/questions:
* Should it be on the top of the [splash page](https://dtf-ein.github.io) as well?
* Since we don't have any pages on the site, the identifier bar is a bit unbalanced.  Once we have main menu items, it'll work.
* I don't like how the FIP repeats in the footer, but right now it's the only spot it appears on the splash.  If we move the FIP to the header of the splash page as well, I could move the "Help us improve" link into the footer to balance things out.
